version: '3.1'

services:

  keycloak:
    image: jboss/keycloak:11.0.2
    command:
      - " -b 0.0.0.0"
    container_name: "keycloak"
    networks:
      - myproject
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "backend"
    environment:
      - spring.oauth2.resourceserver.jwt.issuer-uri= http://keycloak:8080/auth/realms/SpringBootKeycloak
    links:
      - keycloak
    networks:
      - myproject
    restart: on-failure
    ports:
      - "9090:9090"

networks:
  myproject:
    driver: bridge
